export const seedProducts = [
  { name: 'Impresora Bluetooth', category: 'Impresoras Térmicas', price: 250, description: 'Impresora térmica portátil con conexión Bluetooth.' },
  { name: 'Impresora de Etiquetas', category: 'Impresoras Térmicas', price: 450, description: 'Impresora especializada para etiquetas adhesivas.' },
  { name: 'Impresora de Tickets', category: 'Impresoras Térmicas', price: 380, description: 'Impresora térmica de alta velocidad para puntos de venta.' },
  { name: 'Gaveta De Dinero 410G', category: 'Gavetas de Dinero', price: 180, description: 'Gaveta de dinero robusta con apertura automática.' },
  { name: 'Gaveta De Dinero 330R', category: 'Gavetas de Dinero', price: 150, description: 'Gaveta de dinero compacta y resistente.' },
  { name: 'Control de Asistencia EN-818', category: 'Control de Acceso', price: 550, description: 'Sistema de control de asistencia biométrico.' },
  { name: 'Control de Asistencia EN-260', category: 'Control de Acceso', price: 420, description: 'Control de asistencia con tarjeta y clave.' },
  { name: 'Lector de barras MJ2808 1D', category: 'Lector de Código de Barras', price: 120, description: 'Lector de códigos de barras 1D de alta precisión.' },
  { name: 'Lector de barras MJ2808AT 1D', category: 'Lector de Código de Barras', price: 150, description: 'Lector de barras con base automática.' },
  { name: 'Monitor trs156 15.6" FHD', category: 'Monitores Touch', price: 850, description: 'Monitor táctil de 15.6 pulgadas Full HD.' },
  { name: 'Monitor trs215 21.5" FHD', category: 'Monitores Touch', price: 1200, description: 'Monitor táctil de 21.5 pulgadas para uso intensivo.' },
  { name: 'PC de Escritorio i5 12va', category: 'PC O LAPTOP', price: 2200, description: 'Computadora de escritorio potente para oficina y punto de venta.' },
  { name: 'Laptop Pro 15.6"', category: 'PC O LAPTOP', price: 3100, description: 'Laptop de alto rendimiento para gestión de negocios.' },
  { name: 'Etiqueta Térmica Adhesiva 3" x 1.5"', category: 'Suministros', price: 25, description: 'Rollo de etiquetas térmicas adhesivas.' },
  { name: 'Etiqueta Térmica Adhesiva 2" x 1"', category: 'Suministros', price: 20, description: 'Rollo de etiquetas térmicas de 2x1 pulgadas.' },
  { name: 'Papel Contómetro 80mm x 40mm', category: 'Suministros', price: 15, description: 'Papel térmico para impresoras de tickets.' },
  { name: 'Aio 185 pos-star 18.5"', category: 'Terminal Punto de Venta', price: 1800, description: 'Terminal All-in-One de 18.5 pulgadas.' },
  { name: 'Aio JSJ95 Android', category: 'Terminal Punto de Venta', price: 1400, description: 'Terminal punto de venta con sistema Android.' },
  { name: 'Aio A9 con Impresora 8MM', category: 'Terminal Punto de Venta', price: 1650, description: 'Terminal AIO con impresora térmica integrada.' },
  { name: 'Terminal A8 Táctil 11.6"', category: 'Terminal Punto de Venta', price: 1100, description: 'Terminal táctil compacto de 11.6 pulgadas.' },
  { name: 'Terminal 818S Touch 15.6"', category: 'Terminal Punto de Venta', price: 1550, description: 'Terminal táctil profesional de 15.6 pulgadas.' },
  { name: 'Terminal A200S / 80MM + NFC', category: 'Terminal Punto de Venta', price: 1950, description: 'Terminal avanzado con NFC e impresora de 80mm.' },
];
