-- SQL para crear las tablas en Supabase

-- Tabla de productos
CREATE TABLE products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  sku TEXT,
  brand TEXT,
  colors JSONB DEFAULT '[]',
  description TEXT,
  features TEXT,
  price NUMERIC NOT NULL,
  category TEXT,
  image_url TEXT,
  image_urls JSONB DEFAULT '[]',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tabla de pedidos
CREATE TABLE orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_name TEXT NOT NULL,
  customer_whatsapp TEXT NOT NULL,
  customer_address TEXT,
  items JSONB NOT NULL,
  total NUMERIC NOT NULL,
  status TEXT DEFAULT 'pendiente',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Habilitar RLS (Row Level Security)
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;

-- Políticas para productos (Lectura pública, Escritura para todos por ahora para facilitar el demo)
-- NOTA: En producción deberías restringir la escritura a usuarios autenticados.
CREATE POLICY "Permitir lectura pública de productos" ON products FOR SELECT USING (true);
CREATE POLICY "Permitir gestión de productos" ON products FOR ALL USING (true);

-- Políticas para pedidos (Escritura pública para clientes, Lectura para el admin)
CREATE POLICY "Permitir creación de pedidos" ON orders FOR INSERT WITH CHECK (true);
CREATE POLICY "Permitir gestión de pedidos" ON orders FOR ALL USING (true);

-- Tabla de clientes (CRM)
CREATE TABLE customers (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  name TEXT NOT NULL,
  whatsapp TEXT NOT NULL,
  email TEXT,
  last_interaction TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tabla de interacciones
CREATE TABLE interactions (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  customer_id UUID REFERENCES customers(id) ON DELETE CASCADE,
  type TEXT NOT NULL, -- 'whatsapp', 'llamada', 'email'
  content TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Habilitar RLS
ALTER TABLE customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE interactions ENABLE ROW LEVEL SECURITY;

-- Políticas
CREATE POLICY "Permitir gestión de clientes" ON customers FOR ALL USING (true);

-- Tabla de configuración
CREATE TABLE IF NOT EXISTS settings (
  key TEXT PRIMARY KEY,
  value JSONB NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Habilitar RLS
ALTER TABLE settings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir lectura pública de configuración" ON settings FOR SELECT USING (true);
CREATE POLICY "Permitir gestión de configuración" ON settings FOR ALL USING (true);

-- Insertar configuración inicial
INSERT INTO settings (key, value)
VALUES ('general', '{"whatsapp": "", "facebook": "", "instagram": "", "tiktok": "", "logo_url": "", "slides": []}')
ON CONFLICT (key) DO NOTHING;

-- Notificar recarga de esquema
NOTIFY pgrst, 'reload schema';

