-- =========================================================================
-- SCRIPT DE CONFIGURACIÓN COMPLETO DE BASE DE DATOS (SUPABASE / POSTGRESQL)
-- =========================================================================
-- Copia y pega todo este código en el "SQL Editor" de tu consola de Supabase.
--
-- 💡 RESPUESTA SOBRE EL CONFLICTO CON TU WEB PRINCIPAL:
-- -----------------------------------------------------
-- 1. Si tu web principal (ej. WordPress, Shopify, o un sistema interno) usa una 
--    base de datos o proyecto independiente en Supabase, ¡NO habrá ningún conflicto!
--    Dado que Supabase te permite crear proyectos gratis totalmente aislados, te 
--    recomendamos crear un PROYECTO NUEVO en Supabase exclusivo para esta aplicación.
--
-- 2. Si forzosamente necesitas usar el MISMO proyecto de Supabase para tu web principal 
--    y esta landing de ventas, te recomendamos renombrar las tablas agregándoles el prefijo 
--    "pos_" o "landing_" (por ejemplo: "landing_orders", "landing_settings"). 
--    Sin embargo, el diseño actual de esta app ya integra su propio Panel Administrativo (CRM)
--    centralizado para gestionar productos, combos y ver clientes registrados en un solo lugar.
--
-- =========================================================================

-- 1. TABLA: settings (Configuraciones dinámicas y sliders de la interfaz)
CREATE TABLE IF NOT EXISTS settings (
  key TEXT PRIMARY KEY,
  value JSONB NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. TABLA: products (Catálogo de Equipos)
CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  sku TEXT,
  brand TEXT,
  colors JSONB DEFAULT '[]',                      -- Arreglo JS convertido a JSONB
  labels JSONB DEFAULT '[]',                      -- Etiquetas / badges del producto
  description TEXT NOT NULL,
  features TEXT,                                  -- Características técnicas detalladas
  price NUMERIC NOT NULL,
  original_price NUMERIC,                         -- Precio de tachado
  discount NUMERIC,                               -- Porcentaje de descuento
  stock INTEGER DEFAULT 10,
  category TEXT NOT NULL,
  image_url TEXT,                                 -- Imagen principal (Postimages o link directo)
  image_urls JSONB DEFAULT '[]',                  -- Carrusel de imágenes adicionales
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. TABLA: combos (Combos o Packs Promocionales)
CREATE TABLE IF NOT EXISTS combos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT NOT NULL,
  price NUMERIC NOT NULL,
  image_url TEXT,
  product_ids INTEGER[] DEFAULT '{}',             -- Array de IDs de productos asociados
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. TABLA: labels (Etiquetas Personalizables de destaque, ej. "OFERTA", "NUEVO")
CREATE TABLE IF NOT EXISTS labels (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  color TEXT NOT NULL,                            -- Color hexadecimal ej. "#FF3B30"
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. TABLA: orders (Registro de pedidos / Ventas de la tienda y Landers)
CREATE TABLE IF NOT EXISTS orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_name TEXT NOT NULL,
  customer_whatsapp TEXT NOT NULL,
  customer_address TEXT,
  items JSONB NOT NULL,                           -- Lista de {id, name, price, quantity}
  total NUMERIC NOT NULL,
  status TEXT DEFAULT 'pendiente',                -- 'pendiente', 'pagado', 'enviado', 'cancelado'
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 6. TABLA: customers (CRM - Clientes Registrados)
CREATE TABLE IF NOT EXISTS customers (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  name TEXT NOT NULL,
  whatsapp TEXT NOT NULL,
  email TEXT,
  last_interaction TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 7. TABLA: interactions (CRM - Historial de Seguimiento)
CREATE TABLE IF NOT EXISTS interactions (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  customer_id UUID REFERENCES customers(id) ON DELETE CASCADE,
  type TEXT NOT NULL,                             -- 'whatsapp', 'llamada', 'email'
  content TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- =========================================================================
-- ACTIVACIÓN DE ROW LEVEL SECURITY (RLS) & POLÍTICAS
-- =========================================================================
-- Al habilitar RLS permitimos que el público interactúe con lo esencial (ver productos,
-- comprar) y que tus administradores tengan control absoluto de edición.

-- Configurar RLS
ALTER TABLE settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE combos ENABLE ROW LEVEL SECURITY;
ALTER TABLE labels ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE interactions ENABLE ROW LEVEL SECURITY;

-- Políticas de lectura pública universales (Requerido para que los visitantes naveguen)
CREATE POLICY "Lectura pública de settings" ON settings FOR SELECT USING (true);
CREATE POLICY "Lectura pública de products" ON products FOR SELECT USING (true);
CREATE POLICY "Lectura pública de combos" ON combos FOR SELECT USING (true);
CREATE POLICY "Lectura pública de labels" ON labels FOR SELECT USING (true);

-- Permisos de escritura libre para el público (Ventas y Registros)
CREATE POLICY "Cualquiera puede crear pedidos" ON orders FOR INSERT WITH CHECK (true);
CREATE POLICY "Cualquiera puede registrarse como cliente" ON customers FOR INSERT WITH CHECK (true);

-- Permisos totales para el Administrador (Lander Visual Editor y Panel CRM)
CREATE POLICY "Gestión total de settings" ON settings FOR ALL USING (true);
CREATE POLICY "Gestión total de products" ON products FOR ALL USING (true);
CREATE POLICY "Gestión total de combos" ON combos FOR ALL USING (true);
CREATE POLICY "Gestión total de labels" ON labels FOR ALL USING (true);
CREATE POLICY "Gestión de pedidos por admin" ON orders FOR ALL USING (true);
CREATE POLICY "Gestión de clientes de CRM por admin" ON customers FOR ALL USING (true);
CREATE POLICY "Gestión de interacciones por admin" ON interactions FOR ALL USING (true);

-- =========================================================================
-- CARGA DE CONFIGURACIÓN INICIAL DE ESTRELLAS DE CAMPAÑA
-- =========================================================================

-- Registrar configuración del Lander para la Impresora POS-STAR WP200
INSERT INTO settings (key, value)
VALUES (
  'lander_config',
  '{
    "productInfo": {
      "name": "IMPRESORA TERMICA POS-STAR WP200 80MM USB+RJ11",
      "fullName": "IMPRESORA TERMICA POS-STAR WP200 80MM INTERFAZ USB + RJ11 VELOCIDAD 230MM/S con autocorte",
      "price": 203.00,
      "originalPrice": 269.00,
      "discountText": "-24% Desc.",
      "brand": "POS-STAR",
      "model": "WP200",
      "edition": "WP200 Pro-Edition",
      "type": "Impresora Térmica",
      "interface": "USB + RJ11",
      "paperSize": "80MM",
      "speed": "230MM/S",
      "shipping": "Envío a Todo el Perú",
      "deliveryTime": "De 12 a 72 horas",
      "offerType": "Precio solo Web",
      "headerBadgeText": "Oferta Disponible",
      "headerWhatsappText": "905 820 448",
      "whatsappPhone": "51905820448",
      "driverUrl": "https://drive.google.com/drive/folders/1_ejemplo_id_carpeta_drivers",
      "manualUrl": "https://drive.google.com/file/d/1_ejemplo_id_manual_pdf/view",
      "yapePhone": "989 007 409",
      "yapePhoneRaw": "989007409",
      "yapeOwner": "Joaquín García",
      "bcpAccount": "191-1875953-0-18",
      "bcpAccountRaw": "1911875953018",
      "bcpCCI": "002-191-001875953018-53",
      "bcpCCIRaw": "00219100187595301853",
      "bcpOwner": "COPIERMAX EIR.",
      "spec1": "Marca de confianza: POS-STAR (Modelo industrial WP200 de alto rendimiento).",
      "spec2": "Tecnología: Térmica Directa (Cero costos en cartuchos de tinta).",
      "spec3": "Velocidad Profesional: 230 mm/s con sistema de autocorte garantizado.",
      "spec4": "Interfaces integradas: Entrada USB y puerto telefónico RJ11 para comandar gavetas portamonedas."
    },
    "productImages": [
      {
        "url": "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?q=80&w=1000&auto=format&fit=crop",
        "title": "Diseño Frontal POS-STAR WP200",
        "desc": "Estructura robusta de grado industrial optimizada para espacios reducidos en mostradores y cajas."
      },
      {
        "url": "https://images.unsplash.com/photo-1563013544-824ae1d704d3?q=80&w=1000&auto=format&fit=crop",
        "title": "Carga Sencilla de Papel 80mm",
        "desc": "Compartimento de alimentación superior asistido por resortes. Cero atascos y cambio de rollo en 3 segundos."
      },
      {
        "url": "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?q=80&w=1000&auto=format&fit=crop",
        "title": "Velocidad Extrema de 230mm/s",
        "desc": "Su cabezal de impresión térmica de alto rendimiento genera boletas y guías al instante con nitidez impecable."
      },
      {
        "url": "https://images.unsplash.com/photo-1556740758-90de374c12ad?q=80&w=1000&auto=format&fit=crop",
        "title": "Conexión Dual USB + RJ11",
        "desc": "Se conecta directamente a la PC/Laptop y acciona de forma automática la gaveta portamonedas en cada cobro."
      },
      {
        "url": "https://images.unsplash.com/photo-1472851294608-062f824d296e?q=80&w=1000&auto=format&fit=crop",
        "title": "Despacho Garantizado a Nivel Nacional",
        "desc": "Embalaje de fábrica listo para envíos express diarios por Olva, Shalom, Marvisur y más."
      },
      {
        "url": "https://images.unsplash.com/photo-1504274066651-8d31a536b11a?q=80&w=1000&auto=format&fit=crop",
        "title": "Cortador Automático de Acero",
        "desc": "Guillotina de acero aleado de alta precisión capaz de soportar hasta 1.5 millones de cortes limpios."
      }
    ]
  }'
)
ON CONFLICT (key) DO UPDATE
SET value = EXCLUDED.value;

-- Recargar API para capturar cambios de esquema
NOTIFY pgrst, 'reload schema';
